org.ats.entities.Department = maximumSize=500,expireAfterWrite=30m
org.ats.entities.Skill = maximumSize=500,expireAfterWrite=30m
default-query-results-region = maximumSize=200,expireAfterWrite=10m
default-update-timestamps-region = maximumSize=5000,expireAfterWrite=10m